### PR TITLE
Made a lot of changes to make development easier

### PR DESCRIPTION
**Pull request by LordMartron94**
I am not yet done with refactoring into SOLID, but I want you to be able to update more easily without breaking my new architecture. Hence, I already sent this pull request.

Please look it over.

The main things I did so far:
- Made the script loading completely dynamic (requires Python, read the `README_DEV.md`
- Converted all weird Zotero.Zotmoov.X declarations to normal classes so that it's easier to work with.
- Loaded said classes in the bootstrapper startup method.
- Added a debugger that outputs both to the Zotero debugger (you have to enable debug lines in the help section of the Zotero app) and to a log file, by default located in a subfolder (Zotmoov) under the local app data directory. This _should_ be OS-independent, but I'm not entirely sure if that is true, and I can't test in a Linux/MacOS environment, so you have to see if it causes errors for yourself.
- Added the two different versions of Makefile (though this does not work correctly yet for Windows for some weird reason, as mentioned previously)

### CODE REVIEW

**Comment by LordMartron94** [comment]
PS) If you like my changes, you could add me with full access; that way, it's far easier for me to maintain on the base branch together with you.
If we choose to do that, however, it would be very beneficial to connect on Discord or Slack to make the development process easier regarding discussion.

**Comment by wileyyugioh** [comment]
Wow this is very impressive! Yes, I'll be happy to merge this pull request once I review it. I'm pretty busy right now so it'll probably take at most a week or two.

As for giving full access, I'm a little wary since this repo is ultimately pushing code to every user and I want to make sure no malicious code is pushed. Sorry!

**Comment by wileyyugioh** [comment]
I noticed some bugs that I can fix so I will merge the code into the new branch 'rewrite' instead and fix them there. Thanks for your contribution! It was a huge help and the code is much more readable.

**Comment by LordMartron94** [comment]
You're very welcome. I am currently working on making the code even more readable by splitting it into more classes and methods where appropriate. However, this will take some time to get through... especially the wildcard script is a hell 😂

**Pull request merged**
